spring.application.name=backend

# Oracle wallet datasource
spring.datasource.url=jdbc:oracle:thin:@todolistatp_medium?TNS_ADMIN=src/main/resources/wallet
spring.datasource.username=ADMIN
spring.datasource.password=Bubo3003#))#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 8080 is already in use, so we change the default port to 8081
server.port=8081
